/* Licensed under MIT 2021-2024. */
package edu.kit.kastel.mcse.ardoco.id;

public enum MissingElementSupport {
    ELEMENT_WITH_NO_TRACE_LINK, TRACED_ELEMENT_IN_SAME_SENTENCE, DEPENDENCY_TO_TRACED_ELEMENT, MULTIPLE_OVERLAPPING_RECOMMENDED_INSTANCES
}
