name: Maven Deploy (Dev)

on:
  push:
    branches:
      - 'main' # Build the latest develop-SNAPSHOT
    paths:
      - '**/src/**'
      - '**/pom.xml'
      - 'pom.xml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: joshlong/java-version-export-github-action@v17
        id: jve
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ steps.jve.outputs.java_major_version }}
          cache: 'maven'

      - name: Set maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: '[{ "id": "ossrh", "username": "${{ secrets.OSSRH_USER }}", "password": "${{ secrets.OSSRH_TOKEN }}" }]'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}

      - name: Verify with Maven
        run: mvn -U -B verify

      - name: Publish Package
        run: mvn -P deployment -U -B deploy

      - name: Aggregate JavaDocs
        run: mvn -P deployment -U clean javadoc:aggregate

      - name: Disable Jekyll
        run: touch target/site/apidocs/.nojekyll

      - name: Deploy JavaDocs
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: javadoc
          folder: target/site/apidocs/
          repository-name: ArDoCo/Core-Docs
          token: ${{ secrets.SDQ_TOKEN }}
          clean: true
